server:
  port: 8085
spring:
  jpa:
    open-in-view: false
    generate-ddl: true # Whether to initialize the schema on startup.
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/home-budget
    username: user
    password: myPass
    driver-class-name: org.postgresql.Driver

security:
  jwtSecret: thisIsMySecret!
  jwtExpirationInMs: 3600000